name: Cowsay Workflow
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t cowsay:latest .

      - name: Verify Docker Image
        run: |
          docker images | grep cowsay

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name cowsay cowsay:latest
          sleep 5

      - name: Test Application
        run: |
          curl -o /dev/null -s -w "%{http_code}" http://example.com | grep -q 200 || exit 1

      - name: Cleanup
        run: |
          docker stop cowsay
          docker rm cowsay
          
      
